# Generated by Django 5.2.4 on 2026-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_type', models.CharField(choices=[('Phycology', 'Phycology'), ('Motivational', 'Motivational'), ('Technology', 'Technology'), ('Self development', 'self development')], max_length=100)),
                ('book_price', models.IntegerField(max_length=100)),
                ('book_writer', models.CharField(max_length=100)),
                ('book_imag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_color', models.CharField(choices=[('black', 'black'), ('silver', 'silver'), ('red', 'red'), ('white', 'white')], max_length=100)),
                ('car_price', models.IntegerField(max_length=100)),
                ('car_speed', models.IntegerField(max_length=100)),
                ('car_version', models.CharField(max_length=100)),
                ('car_images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop_name', models.CharField(max_length=100)),
                ('laptop_model', models.CharField(max_length=100)),
                ('laptop_color', models.CharField(choices=[('black', 'black'), ('silver', 'silver'), ('gold', 'gold'), ('skyblue', 'skyblue')], max_length=100)),
                ('laptop_price', models.IntegerField(max_length=100)),
                ('laptop_storage', models.IntegerField(max_length=100)),
                ('laptop_type', models.CharField(max_length=100)),
                ('laptop_images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=100)),
                ('mobile_model', models.CharField(max_length=100)),
                ('mobile_color', models.CharField(choices=[('black', 'black'), ('silver', 'silver'), ('gold', 'gold'), ('skyblue', 'skyblue')], max_length=100)),
                ('mobile_price', models.IntegerField(max_length=100)),
                ('mobile_storage', models.IntegerField(max_length=100)),
                ('mobile_version', models.CharField(max_length=100)),
                ('mobile_images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resume', models.ImageField(upload_to='images/')),
                ('fees', models.IntegerField(max_length=100)),
            ],
        ),
    ]
