# Generated by Django 5.2.4 on 2026-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_images1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_images2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_images3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
