# Generated by Django 5.2.4 on 2026-08-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ImageField(upload_to='old_car')),
                ('name', models.CharField(max_length=50)),
                ('speed', models.IntegerField(max_length=50)),
                ('model', models.IntegerField(max_length=50)),
                ('brand', models.IntegerField(max_length=50)),
                ('price', models.IntegerField(max_length=200)),
                ('car_about', models.TextField(max_length=200)),
            ],
        ),
    ]
